### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by anieminen** [UbiCastTeam/moodle-mod_easycastms#3]
Hi,

How does access control work when a user selects media from the activity? I am logged in to Moodle with a username, that does not exist in MediaServer. But I am able to browse every channel and video on the MediaServer, although there are also some channels & videos that are set as "unlisted". I cannot play any unpublished videos, but I am able to browse and select them from the "Select a media" link.

**Comment by fthiery** [comment]
Hi; the username must exist both in MediaServer and Moodle, and have the appropriate permissions: in other terms, you must define the permissions in MediaServer as well. This is usually achieved through groups in MediaServer (e.g. first year math students, ...) which grant access to the parent channel in MediaServer (e.g. /Y1/math). In other terms, this plugin does not enable SSO (yet).

If you are looking for a more transparent solution that does implement an actual SSO, please take a look at LTI directly; once the activity setup in Moodle and MediaServer appropriately, and the student and teacher roles created, Moodle with grant access to the media automatically.

There is a possibility of using LTI within this building block, which would add transparent SSO to the current building block, but the funding of this feature has not been found yet; if you are willing to fund it, please contact us at presales@ubicast.eu.
